spring:
  profiles.active: local


---
spring:
  profiles: local

  mvc:
    throw-exception-if-no-handler-found: true
  output:
    ansi:
      enabled: always
  resources:
    add-mappings: false

  rabbitmq:
    host: 172.16.0.45
    port: 5672
    username: admin
    password: admin

  redis:
    host: 172.16.0.27
    port: 19000



zookeeper:
  zookeeperAddress: 172.16.0.50:2181,172.16.0.26:2181,172.16.0.27:2181
  serviceName: order-services  #服务名称
  basePath: /order   #服务根路径
  servicePath: /order-services  #服务注册路径
  lockPath: /order/lock  #分布式锁路径


kafka:
  bootstrap-servers: 172.16.0.30:9093, 172.16.0.31:9093, 172.26.0.32:9093
  topics: db_order_new  #用el表达式解析，中间不能有空格
  concurrency: 2
  legacyGroupID: canal_sync_legacy_dohko
  userGroupID: canal_sync_user_dohko
  orderStatusGroupID: canal_order_status_dohko

datasource:
  url: jdbc:mysql://localhost:3306/lxy-demo
  username: root
  password: root
  driverClassName: com.mysql.jdbc.Driver
  initialSize: 2
  maxActive: 4
  minIdle: 1
  validationQuery: SELECT 1

redisStock:
  host: codis.test.hualala.com
  port: 19000
  db: 0
  pool:
    maxActive: 10
    maxWait: 10000
    writeTimeout: 1000
    readTimeout: 1000
    maxIdle: 5
    minIdle: 5

rabbitmq:
  orderStatusExchangeName: hll:service:order:status:machine:exchang
  orderStatusTopicExchangeName: hll:service:order:status:machine:topicexchange
  orderStatusTestTopicQueueName : hll:service:order:status:machine:saas:sub_buffet:test
  routeKeyPrefix: order.statusmachine
  # 线上不能使用 存在的ordeType ，防止消息积压或者被测试类消费掉
  routeKey: order.*
  orderStatusTestTopicQueueNoConsumeName : hll:service:order:status:machine:no:consume #  测试只写入queue 不消费
  routeKeyNoConsume: lxy.test.no.*



logging:
  config: classpath:logback-local.xml



